name: Java CI with Gradle

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Granting Permission to gradlew
      run: chmod +x gradlew

    - name: Run test with gradlew
      run: ./gradlew test

    - name: Report jacocoTestCoverage
      uses: Madrapps/jacoco-report@v1.6.1
      with: 
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.ACCESS_TOKEN }}
        title: Test Coverage
        min-coverage-overall: 100
        min_coverage-changed-files: 100
